# Generated by Django 5.2.5 on 2025-08-12 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.area')),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')], default=0)),
                ('birthday', models.DateField(blank=True)),
                ('is_looking', models.BooleanField(default=False)),
                ('has_house', models.BooleanField(default=False)),
                ('major_city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='room.area')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
